[target.x86_64-unknown-linux-gnu]
# SSE3 is requred by simd-varint. tokio_unstable is for tokio-console.
rustflags = ["-C", "target-feature=+avx2"]

[target.x86_64-apple-darwin]
# SSE3 is requred by simd-varint. tokio_unstable is for tokio-console.
rustflags = ["-C", "target-feature=+avx2"]
